datafile <- read.table(file="household_power_consumption.txt", sep = ";", header=T)
filter_data <- datafile[datafile$Date == "1/2/2007" | datafile$Date == "2/2/2007",]
t <- paste(filter_data$Date, filter_data$Time)
t <- strptime(t, "%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(as.numeric(t), as.numeric(filter_data$Sub_metering_1), type="l", ylab="Enegry sub metering", xlab="")
lines(as.numeric(t), as.numeric(filter_data$Sub_metering_2), type="l", col="red")
lines(as.numeric(t), as.numeric(filter_data$Sub_metering_3), type="l", col="blue")
legend("topright", col=c("black", "red", "blue"), pch="-", legend=c("Sub_meterimg_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
